package com.automation.framework.tasks;

import javax.mail.*;
import javax.mail.internet.*;
import java.util.Properties;

public class EmailSender {

    public static void sendEmail(String toEmail, String emailBody) {
        // Gmail credentials
        String fromEmail = "reminder.noreplyauto@gmail.com"; // Sender's email address (Gmail)
        String host = "smtp.gmail.com"; // Gmail SMTP server address
        final String username = "reminder.noreplyauto@gmail.com"; // Gmail username (your email address)
        final String password = "Abc1234@"; // Gmail password

        // Set email properties for Gmail
        Properties properties = new Properties();
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "587"); // 587 for TLS (use 465 for SSL)
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true"); // Use TLS

        // Create a Session with authentication
        Session session = Session.getInstance(properties, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password); // Return Gmail username and password
            }
        });

        try {
            // Create a MimeMessage
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(fromEmail)); // From address
            message.setRecipient(Message.RecipientType.TO, new InternetAddress(toEmail)); // Recipient address
            message.setSubject("Automated Alert Notification"); // Email subject
            message.setText(emailBody); // Email body (content)

            // Set a "Reply-To" header to make it a no-reply email
            message.setHeader("Reply-To", "no-reply@yourdomain.com");

            // Send the email
            Transport.send(message); // Send the message
            System.out.println("Email sent successfully.");
        } catch (MessagingException e) {
            e.printStackTrace();
            System.out.println("Failed to send email.");
        }
    }

    public static void main(String[] args) {
        // Example usage: Send an email with an input string as the body
        String recipientEmail = "srinivas.seniordeveloper@gmail.com"; // Receiver's email address
        String emailContent = "This is an alert message generated by the system.";
        
        sendEmail(recipientEmail, emailContent); // Send the email
    }
}
